-- MySQL Script generated by MySQL Workbench
-- Mon Jul 24 13:07:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rental Car Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental Car Inventory` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `maxPassenger` INT NOT NULL,
  `vin#` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `pricing` DECIMAL(45) NOT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car Reservation` (
  `reservationCode` VARCHAR(45) NOT NULL,
  `car_id` INT NOT NULL,
  `origin` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `arrivalTime` DATETIME NOT NULL,
  `departureTime` DATETIME NOT NULL,
  PRIMARY KEY (`reservationCode`),
  INDEX `car_id_idx` (`car_id` ASC),
  CONSTRAINT `car_id`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`Rental Car Inventory` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `airport_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `airportCode` VARCHAR(45) NULL,
  PRIMARY KEY (`airport_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport Parking Spaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport Parking Spaces` (
  `parkingSpace_Id` INT NOT NULL,
  `airport_Id` INT NOT NULL,
  `isVip` TINYINT NOT NULL,
  `parkingIdentifier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`parkingSpace_Id`),
  INDEX `airport_id_idx` (`airport_Id` ASC),
  CONSTRAINT `airport_id`
    FOREIGN KEY (`airport_Id`)
    REFERENCES `mydb`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft` (
  `aircraft_id` INT NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aircraft_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flights` (
  `flight_no` INT NOT NULL,
  `aircraft_id` INT NOT NULL,
  `origin_id` INT NOT NULL,
  `destination_id` INT NOT NULL,
  `departureTime` DATETIME NOT NULL,
  `arrivalTime` DATETIME NOT NULL,
  `economyRate` DECIMAL(10) NOT NULL,
  `firstClassRate` DECIMAL(10) NOT NULL,
  `businessRate` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`flight_no`),
  INDEX `aircraft_id_idx` (`aircraft_id` ASC),
  CONSTRAINT `aircraft_id`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `mydb`.`Aircraft` (`aircraft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parking Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parking Reservation` (
  `order_id` INT NOT NULL,
  `parkingSpace_id` INT NOT NULL,
  `startReservationDate` DATETIME NOT NULL,
  `endReservationDate` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `parkingSpace_id_idx` (`parkingSpace_id` ASC),
  CONSTRAINT `parkingSpace_id`
    FOREIGN KEY (`parkingSpace_id`)
    REFERENCES `mydb`.`Airport Parking Spaces` (`parkingSpace_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft Default Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft Default Seats` (
  `default_id` INT NOT NULL,
  `seat_id` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`default_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight Seats` (
  `seat_id` VARCHAR(45) NOT NULL,
  `flight_no` INT NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `customer_id` INT NOT NULL,
  `assignedToName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `flight_no_idx` (`flight_no` ASC),
  CONSTRAINT `flight_no`
    FOREIGN KEY (`flight_no`)
    REFERENCES `mydb`.`Flights` (`flight_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `customer_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phone#` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Credit Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Credit Card` (
  `number` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `securityCode` INT NOT NULL,
  `expirationDate` VARCHAR(45) NOT NULL,
  `billingStreetAddress` VARCHAR(45) NOT NULL,
  `billingStreetAddress2` VARCHAR(45) NOT NULL,
  `billingCity` VARCHAR(45) NOT NULL,
  `billingState` VARCHAR(45) NOT NULL,
  `billingZip` INT NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
