-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 15:40:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rental_car_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rental_car_inventory` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `maxPassenger` INT NOT NULL,
  `vin#` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `pricing` DECIMAL(45) NOT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airport` (
  `airport_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `airportCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airport_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car_reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `reservationCode` VARCHAR(45) NOT NULL,
  `car_id` INT NOT NULL,
  `origin` INT NOT NULL,
  `destination` INT NOT NULL,
  `departureTime` DATETIME NOT NULL,
  `arrivalTime` DATETIME NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `car_id_idx` (`car_id` ASC),
  INDEX `fk_origin_to_arport_idx` (`origin` ASC),
  INDEX `fk_destination_to_airport_idx` (`destination` ASC),
  CONSTRAINT `fk_carres_to_carinv`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`rental_car_inventory` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_origin_to_airport`
    FOREIGN KEY (`origin`)
    REFERENCES `mydb`.`airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destination_to_airport`
    FOREIGN KEY (`destination`)
    REFERENCES `mydb`.`airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airport_parking_spaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airport_parking_spaces` (
  `parkingSpace_id` INT NOT NULL AUTO_INCREMENT,
  `airport_id` INT NOT NULL,
  `isVip` BIT(20) NOT NULL,
  `parkingIdentifier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`parkingSpace_id`),
  INDEX `airport_id_idx` (`airport_id` ASC),
  CONSTRAINT `fk_parking_to_airport`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aircraft` (
  `aircraft_id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aircraft_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flights` (
  `flight_id` INT NOT NULL AUTO_INCREMENT,
  `aircraft_id` INT NOT NULL,
  `origin_id` INT NOT NULL,
  `destination_id` INT NOT NULL,
  `flight_num` VARCHAR(45) NOT NULL,
  `departureTime` DATETIME NOT NULL,
  `arrivalTime` DATETIME NOT NULL,
  `economyRate` DECIMAL(10) NOT NULL,
  `firstClassRate` DECIMAL(10) NOT NULL,
  `businessRate` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `aircraft_id_idx` (`aircraft_id` ASC),
  INDEX `fk_destination_id_to_airport_idx` (`destination_id` ASC),
  INDEX `fk_origin_id_to_airport_idx` (`origin_id` ASC),
  CONSTRAINT `fk_flight_to_aircraft`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `mydb`.`aircraft` (`aircraft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_origin_id_to_airport`
    FOREIGN KEY (`origin_id`)
    REFERENCES `mydb`.`airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destination_id_to_airport`
    FOREIGN KEY (`destination_id`)
    REFERENCES `mydb`.`airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parking_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parking_reservation` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `parkingSpace_id` INT NOT NULL,
  `startReservationDate` DATETIME NOT NULL,
  `endReservationDate` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `parkingSpace_id_idx` (`parkingSpace_id` ASC),
  CONSTRAINT `fk_parkres_to_space`
    FOREIGN KEY (`parkingSpace_id`)
    REFERENCES `mydb`.`airport_parking_spaces` (`parkingSpace_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aircraft_default_seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aircraft_default_seats` (
  `default_id` INT NOT NULL AUTO_INCREMENT,
  `seat_num` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`default_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `phone#` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `addr1` VARCHAR(45) NULL,
  `addr2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight_seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight_seats` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `flight_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `seat_num` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `assignedToName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `flight_no_idx` (`flight_id` ASC),
  INDEX `fk_customer_id_to_customers_idx` (`customer_id` ASC),
  CONSTRAINT `fk_seat_to_flight`
    FOREIGN KEY (`flight_id`)
    REFERENCES `mydb`.`flights` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_id_to_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_order_to_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_card` (
  `cc_id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(16) NOT NULL,
  `customer_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `securityCode` INT NOT NULL,
  `expirationDate` VARCHAR(45) NOT NULL,
  `billingStreetAddress` VARCHAR(45) NOT NULL,
  `billingStreetAddress2` VARCHAR(45) NOT NULL,
  `billingCity` VARCHAR(45) NOT NULL,
  `billingState` VARCHAR(45) NOT NULL,
  `billingZip` INT NOT NULL,
  PRIMARY KEY (`cc_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_cc_to_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;